Update 0-give_me_a_page

diff --git a/0x0D-web_stack_debugging_0/0-give_me_a_page b/0x0D-web_stack_debugging_0/0-give_me_a_page
--- a/0x0D-web_stack_debugging_0/0-give_me_a_page
+++ b/0x0D-web_stack_debugging_0/0-give_me_a_page
@@ -1,4 +1,9 @@
 #!/usr/bin/env bash
 
-# Create a file named index.html in the assumed document root (/var/www/html)
+# Try creating the index.html file in a common document root location
 echo "Hello Holberton" > /var/www/html/index.html
+
+# If the previous command fails, create the file in a more generic location (fallback)
+if [ $? -ne 0 ]; then
+  echo "Hello Holberton" > /usr/share/nginx/html/index.html  # Assuming Nginx might also be used
+fi
